FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /app

COPY . . 

RUN mvn clean package -DskipTests


FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY --from=build /app/target/quarkus-app /app/quarkus-app

EXPOSE 8080

CMD ["java", "-jar", "quarkus-app/quarkus-run.jar"]